[project]
name = "harmonyalign"
version = "0.1.0"
description = ""
dependencies = [
    "numpy",
    "scipy",
    "mrcfile",
    "starfile",
    "pandas",
    "spherical",
    "pytest"
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]